// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Eyeing Art",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Eyeing Art",
            targets: ["AppModule"],
            bundleIdentifier: "Ryu.Tracking",
            teamIdentifier: "YKG7843K2L",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "To track the face using AR capabilities, the app accesses the camera."),
                .photoLibraryAdd(purposeString: "To save the picture to the photo library, the app accesses the photos.")
            ],
            appCategory: .lifestyle
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)